# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atmosphere', models.IntegerField()),
                ('food', models.IntegerField()),
                ('facilities', models.IntegerField()),
                ('additionalInfo', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('totalScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(height_field=100, upload_to='stadium_images', width_field=100)),
                ('capacity', models.IntegerField()),
                ('postcode', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('homeTeam', models.CharField(max_length=55)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'stadiums',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stadium',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATGApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATGApp.Stadium'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATGApp.UserProfile'),
        ),
    ]
