# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATGApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='ReviewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadium',
            name='TotalScore',
            field=models.IntegerField(default=0),
        ),
    ]
