# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATGApp', '0003_auto_20190301_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='totalScore',
            field=models.IntegerField(blank=True),
        ),
    ]
