# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATGApp', '0005_auto_20190303_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='photo',
            field=models.ImageField(blank=True, upload_to='stadium_images'),
        ),
    ]
