# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-03 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATGApp', '0006_auto_20190303_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='atmosphere',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='facilities',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
