# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATGApp', '0007_auto_20190303_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='averageScore',
            field=models.IntegerField(default=0),
        ),
    ]
