# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATGApp', '0008_stadium_averagescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='postcode',
            field=models.CharField(max_length=30),
        ),
    ]
