# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATGApp', '0008_stadium_averagescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='latitude',
            field=models.CharField(default=b'1', max_length=100),
        ),
        migrations.AddField(
            model_name='stadium',
            name='longitude',
            field=models.CharField(default=b'1', max_length=100),
        ),
    ]
