# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATGApp', '0009_auto_20190319_1501'),
        ('ATGApp', '0009_auto_20190319_1326'),
    ]

    operations = [
    ]
